module.exports = {
    // service: 'Outlook365',
    // host: 'smtp.office365.com',
    // port: '587',
    // user: "vms@hisysmc.com",
    // pass: "May64863", 
    // service: 'gmail',
  apiKey:'Replace-Apikey',
  name: "Hitachi-systems",
  email: "hitachi.p2p@hisysmc.com",
  // email: "sudhir.kumar.dp@hitachi-systems.com",
  // VctTeamEmail:"VND-APPV-1@hitachi-systems.com",
  // MrtTeamEmail:"VND-APPV-3@hitachi-systems.com",
  // JapanTeamEmail:"VND-APPV-2@hitachi-systems.com",
  VctTeamEmail:"mohanrajr@mavdero.in",
  MrtTeamEmail:"mohanrajr@mavdero.in",
  JapanTeamEmail:"mohanrajr@mavdero.in",
  //   VctTeamEmail:"karthigapalani@mavdero.in",
  // MrtTeamEmail:"karthigapalani@mavdero.in",
  // JapanTeamEmail:"karthigapalani@mavdero.in",
  };